spring:
  application:
    name: task-api
  datasource:
    url: jdbc:postgresql://localhost:5432/task-db
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true
    validate-on-migrate: true
    schemas: tms
    create-schemas: true