spring:
  flyway:
    clean-disabled: false
  jpa:
    show-sql: true
jwt:
  secret: ${JWT_SECRET:bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25UaGF0SXNBdExlYXN0MjU2Qml0c0xvbmVGb3JIUzI1NkFsZ29yaXRobQ==}
  expiration: ${JWT_EXPIRATION:86400000}